# Generated by Django 4.1.7 on 2023-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='employee',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
